#if !canImport(ObjectiveC)
import XCTest

extension Swift_CRC32Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Swift_CRC32Tests = [
        ("test192BitValue", test192BitValue),
        ("testSimpleData", testSimpleData),
        ("testSimpleNumbersCRC32", testSimpleNumbersCRC32),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Swift_CRC32Tests.__allTests__Swift_CRC32Tests),
    ]
}
#endif
