#if !canImport(ObjectiveC)
import XCTest

extension CRCByteBufferTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CRCByteBufferTests = [
        ("testSimpleData", testSimpleData),
        ("testSimpleNumbersCRC32", testSimpleNumbersCRC32),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CRCByteBufferTests.__allTests__CRCByteBufferTests),
    ]
}
#endif
